### ISSUE TITLE
能否实现自动生成Cookie参数？

### ISSUE THREAD

**Issue by njbaige** [HarcicYang/rev_Baichuan#1]
能否实现通过提供baichuan用户名密码，自动生成Cookie参数？
避免Cookie过期的问题，谢谢！

**Comment by HarcicYang** [comment]
emmm，我理解你的需求，但是下次再提问时希望您多参考一下实际情况。

百川智能目前没有开放账号密码登录，登陆时只能使用短信验证码，这并不会比你手动获取cookie更轻松；并且百川的cookie有效期似乎很长。因此我不认为有必要开发这样一个功能
